# Generated by Django 5.2.5 on 2025-08-12 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unikalna nazwa agenta, np. 'Generalista'", max_length=100, unique=True)),
                ('agent_type', models.CharField(choices=[('general', 'Generalista'), ('specialized', 'Specjalista'), ('assistant', 'Asystent'), ('analyzer', 'Analityk')], default='general', max_length=20)),
                ('persona_prompt', models.TextField(help_text='Opis osobowości i zadania agenta, który będzie używany w promptach LLM.')),
                ('system_prompt', models.TextField(blank=True, help_text='Systemowy prompt dla agenta')),
                ('capabilities', models.JSONField(default=list, help_text='Lista zdolności agenta')),
                ('config', models.JSONField(default=dict, help_text='Konfiguracja agenta')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['agent_type', 'is_active'], name='chatbot_age_agent_t_0efd11_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.CharField(blank=True, help_text='ID użytkownika (opcjonalne)', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Tytuł konwersacji', max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Podsumowanie konwersacji')),
                ('metadata', models.JSONField(default=dict, help_text='Dodatkowe dane konwersacji')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbot.agent')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Użytkownik'), ('assistant', 'Agent/Asystent'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Metadata wiadomości (tokeny, model, itp.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session_id'], name='chatbot_con_session_6c660a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agent', 'is_active'], name='chatbot_con_agent_i_ace777_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='chatbot_con_created_e6d9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_b353f0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='chatbot_mes_role_028558_idx'),
        ),
    ]
