# Generated by Django 5.2.5 on 2025-08-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('general', 'Generalista'), ('specialized', 'Specjalista'), ('assistant', 'Asystent'), ('analyzer', 'Analityk'), ('ollama', 'Ollama'), ('rag', 'RAG Agent')], default='general', max_length=20),
        ),
    ]
