# Generated by Django 5.2.5 on 2025-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_agent_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('router', 'Router Agent'), ('ollama', 'Ollama (Legacy)')], default='general', max_length=20),
        ),
    ]
