# Generated by Django 5.2.5 on 2025-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_agent_agent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nazwa produktu')),
                ('quantity', models.FloatField(default=1.0, verbose_name='Ilość')),
                ('unit', models.CharField(default='szt.', max_length=50, verbose_name='Jednostka')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Produkt w spiżarni',
                'verbose_name_plural': 'Produkty w spiżarni',
                'ordering': ['-updated_date'],
            },
        ),
    ]
