# Generated by Django 5.2.5 on 2025-08-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_pantryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='receipt_images/', verbose_name='Obraz paragonu')),
                ('status', models.CharField(choices=[('uploaded', 'Przesłany'), ('ocr_in_progress', 'OCR w toku'), ('ocr_done', 'OCR zakończony'), ('llm_in_progress', 'LLM w toku'), ('llm_done', 'LLM zakończony'), ('ready_for_review', 'Gotowy do recenzji'), ('completed', 'Zakończony'), ('error', 'Błąd')], default='uploaded', max_length=20, verbose_name='Status przetwarzania')),
                ('raw_ocr_text', models.TextField(blank=True, verbose_name='Surowy tekst z OCR')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='Wyodrębnione dane (JSON)')),
                ('error_message', models.TextField(blank=True, verbose_name='Komunikat błędu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przesłania')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data przetworzenia')),
            ],
            options={
                'verbose_name': 'Przetwarzanie paragonu',
                'verbose_name_plural': 'Przetwarzanie paragonów',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data ważności'),
        ),
    ]
