# Generated by Django 5.2.5 on 2025-08-14 11:56

from django.db import migrations, models

import chatbot.validators


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_receiptprocessing_pantryitem_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptprocessing',
            name='receipt_image',
        ),
        migrations.AddField(
            model_name='receiptprocessing',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Obsługiwane formaty: JPG, PNG, WebP, PDF (maks. 10MB)', null=True, upload_to='receipt_files/', validators=[chatbot.validators.validate_receipt_file], verbose_name='Plik paragonu (obraz lub PDF)'),
        ),
    ]
