# Generated by Django 5.2.5 on 2025-08-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_add_receipt_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptprocessing',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Plik przesłany'), ('ocr_in_progress', 'Rozpoznawanie tekstu (OCR)'), ('ocr_done', 'Tekst rozpoznany'), ('llm_in_progress', 'Analiza przez AI'), ('llm_done', 'Analiza zakończona'), ('ready_for_review', 'Gotowe do weryfikacji'), ('completed', 'Zakończone'), ('error', 'Wystąpił błąd')], default='uploaded', max_length=20, verbose_name='Status przetwarzania'),
        ),
    ]
