# Generated by Django 5.2.5 on 2025-08-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_alter_receiptprocessing_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='chatbot_doc_status_cd3d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='chatbot_doc_uploade_dd1eea_idx'),
        ),
        migrations.AddIndex(
            model_name='pantryitem',
            index=models.Index(fields=['expiry_date'], name='chatbot_pan_expiry__767839_idx'),
        ),
        migrations.AddIndex(
            model_name='pantryitem',
            index=models.Index(fields=['updated_date'], name='chatbot_pan_updated_7e0a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptprocessing',
            index=models.Index(fields=['status'], name='chatbot_rec_status_743ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptprocessing',
            index=models.Index(fields=['uploaded_at'], name='chatbot_rec_uploade_4c8842_idx'),
        ),
    ]
