# Generated by Django 5.2.5 on 2025-08-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0012_document_chatbot_doc_status_cd3d3d_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name='PantryItem',
        ),
    ]
