# Generated by Django 5.2.5 on 2025-08-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0015_data_migration_receipts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReceiptProcessing",
        ),
    ]
