# Generated by Django 5.2.5 on 2025-08-20 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0016_delete_receiptprocessing"),
        ("inventory", "0007_alter_receipt_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_product_name",
                    models.CharField(
                        help_text="The product name as initially extracted by OCR/LLM.",
                        max_length=255,
                    ),
                ),
                (
                    "corrected_product_name",
                    models.CharField(
                        help_text="The product name as corrected by the user.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="The product that the user matched the item to (if existing).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections_as_matched",
                        to="inventory.product",
                    ),
                ),
                (
                    "receipt_line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="inventory.receiptlineitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who made the correction.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Correction",
                "verbose_name_plural": "Product Corrections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["original_product_name"],
                        name="chatbot_pro_origina_5ac902_idx",
                    ),
                    models.Index(
                        fields=["corrected_product_name"],
                        name="chatbot_pro_correct_43e9e2_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="chatbot_pro_created_489355_idx"
                    ),
                ],
            },
        ),
    ]
