# Generated by Django 5.2.5 on 2025-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict, help_text='Parsed structured data from receipt text'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending_ocr', 'Pending OCR'), ('processing_ocr', 'OCR in Progress'), ('ocr_completed', 'OCR Completed'), ('processing_parsing', 'Processing Parsing'), ('parsing_completed', 'Parsing Completed'), ('matching', 'Matching Products'), ('completed', 'Completed'), ('error', 'Error')], default='pending_ocr', max_length=20),
        ),
    ]
