# Generated by Django 5.2.5 on 2025-08-17 14:17

from decimal import Decimal

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_receipt_parsed_data_alter_receipt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Komunikat błędu"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="extracted_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Wyodrębnione dane (JSON)"
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data przetworzenia"
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="raw_ocr_text",
            field=models.TextField(blank=True, verbose_name="Surowy tekst z OCR"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                help_text="Obsługiwane formaty: JPG, PNG, WebP, PDF (maks. 10MB)",
                null=True,
                upload_to="receipt_files/",
                verbose_name="Plik paragonu (obraz lub PDF)",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="uploaded_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data przesłania"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="purchased_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the receipt was issued",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="source_file_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to original receipt file",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Plik przesłany"),
                    ("pending_ocr", "Pending OCR"),
                    ("processing_ocr", "OCR in Progress"),
                    ("ocr_in_progress", "Rozpoznawanie tekstu (OCR)"),
                    ("ocr_completed", "OCR Completed"),
                    ("ocr_done", "Tekst rozpoznany"),
                    ("processing_parsing", "Processing Parsing"),
                    ("llm_in_progress", "Analiza przez AI"),
                    ("llm_done", "Analiza zakończona"),
                    ("parsing_completed", "Parsing Completed"),
                    ("matching", "Matching Products"),
                    ("ready_for_review", "Gotowe do weryfikacji"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount from receipt",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
