# Generated by Django 5.2.5 on 2025-08-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_receipt_error_message_receipt_extracted_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="processing_step",
            field=models.CharField(
                choices=[
                    ("uploaded", "File Uploaded"),
                    ("ocr_in_progress", "OCR in Progress"),
                    ("ocr_completed", "OCR Completed"),
                    ("parsing_in_progress", "Parsing in Progress"),
                    ("parsing_completed", "Parsing Completed"),
                    ("matching_in_progress", "Matching Products"),
                    ("matching_completed", "Matching Completed"),
                    ("finalizing_inventory", "Finalizing Inventory"),
                    ("review_pending", "Review Pending"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                help_text="Current granular step in the receipt processing pipeline",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Processing"),
                    ("processing", "Processing in Progress"),
                    ("ready_for_review", "Ready for Review"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
