# Generated by Django 5.2.5 on 2025-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_receipt_processing_step_alter_receipt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Processing"),
                    ("pending_ocr", "Pending OCR"),
                    ("processing", "Processing in Progress"),
                    ("processing_ocr", "OCR in Progress"),
                    ("ocr_completed", "OCR Completed"),
                    ("processing_parsing", "Processing Parsing"),
                    ("parsing_completed", "Parsing Completed"),
                    ("matching", "Matching Products"),
                    ("ready_for_review", "Ready for Review"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
