# Generated by Django 5.2.5 on 2025-08-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_receipt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Oczekuje"),
                    ("processing", "W trakcie przetwarzania"),
                    ("review_pending", "Oczekuje na weryfikację"),
                    ("completed", "Zakończono"),
                    ("error", "Błąd"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
