# Generated by Django 5.2.5 on 2025-08-20 14:54

from django.db import migrations, models
from django.utils import timezone


def convert_aliases_to_json_structure(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    for product in Product.objects.all():
        if product.aliases and isinstance(product.aliases[0], str):
            new_aliases = []
            for alias_name in product.aliases:
                now = timezone.now().isoformat()
                new_aliases.append({
                    "name": alias_name,
                    "count": 1,
                    "first_seen": now,
                    "last_seen": now,
                    "status": "unverified"
                })
            product.aliases = new_aliases
            product.save(update_fields=['aliases'])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_receipt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of dictionaries, each representing an alias with its metadata (name, count, first_seen, last_seen, status).",
            ),
        ),
        migrations.RunPython(convert_aliases_to_json_structure, reverse_code=migrations.RunPython.noop),
    ]
