# Generated by Django 5.2.5 on 2025-08-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_product_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("condition", models.JSONField()),
                ("action", models.JSONField()),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Niższa liczba = wyższy priorytet"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
    ]
