# Generated by Django 5.2.5 on 2025-08-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcrCorrectionPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_pattern",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("correct_pattern", models.CharField(max_length=255)),
                ("confidence_score", models.FloatField()),
                ("times_applied", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="OcrTrainingSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_ocr_text", models.TextField()),
                ("ground_truth_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.receipt",
                    ),
                ),
            ],
        ),
    ]
