# Generated by Django 5.2.5 on 2025-08-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_ocrcorrectionpattern_ocrtrainingsample"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="task_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Celery task ID for async processing",
                max_length=255,
            ),
        ),
    ]
