name: CI Pipeline

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black mypy django-stubs
    
    - name: Run ruff linting
      run: ruff check .
    
    - name: Run black formatting check
      run: black --check .
    
    - name: Run mypy type checking
      run: mypy .

  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr libmagic1
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment
      run: |
        cp .env.example .env || echo "DATABASE_URL=sqlite:///test.db" > .env
        echo "CELERY_BROKER_URL=redis://localhost:6379/0" >> .env
        echo "CACHE_URL=redis://localhost:6379/1" >> .env
        echo "DEBUG=True" >> .env
    
    - name: Run migrations
      run: |
        python manage.py migrate --settings=core.settings_dev
    
    - name: Run tests with coverage
      run: |
        coverage run --source='.' manage.py test --settings=core.settings_dev
        coverage xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  performance-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr libmagic1
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment
      run: |
        echo "DATABASE_URL=sqlite:///test.db" > .env
        echo "DEBUG=True" >> .env
    
    - name: Run performance tests
      run: |
        python manage.py test inventory.tests_performance --settings=core.settings_dev -v 2
